/*
 * lines.js — one line per day, set down on July 3, 2026.
 *
 * There are exactly 182 — one for every day from the planting of the
 * tree to the opening of the letter. They were all written the night
 * the site was rebuilt, so each day's line has been waiting for its
 * date ever since. After December 31, 2026, they return in order,
 * like a tide.
 */

import { daysBetween } from './astro.js';
import { PLANTED } from './grove.js';

export const LINES = [
  /* — July 3–31 : setting it down — */
  'The bravest thing you did this year was hand over the keys and rest.',
  'A field left fallow is not a field abandoned.',
  'Nothing built in a hurry knows how to hold still. Learn from what you make.',
  'Today the harbor did six billion things and asked credit for none of them.',
  'Rest is not the opposite of work. It is the part of the work you kept skipping.',
  'The sun took fifteen hours to cross Boston today and never once checked its pace.',
  'You are allowed to be a beginner again. It is the fastest way back.',
  'A losing battle is often just the wrong battle, fought bravely.',
  'The tide goes out twice a day and has never once been called a quitter.',
  'Do the small thing fully. The big thing is made of nothing else.',
  'July does not envy October. Stand where you are.',
  'What you water grows. Check what you have been watering.',
  'The city looks finished from the bridge. Up close it is all scaffolding. So are you.',
  'Nobody claps for the lighthouse keeper. The ships arrive anyway.',
  'You cannot rush a tree. You can only keep it alive and stay interested.',
  'Half of mastery is staying calm while being bad at something.',
  'The Charles has been rerouted, dammed, and doubted. It is still the river.',
  'The sky is doing something right now that will never repeat. Look up.',
  'Being unknown is a kind of freedom you will miss when it is gone.',
  'An unwatched pot boils fine. It always did.',
  'Make one true thing a day. The weeks will handle themselves.',
  'The fog does not fight the sun. It just gets to be first.',
  'Old brick holds the day\u2019s heat long into the night. Be like that with joy.',
  'If it can be done angry, it can be done calm, and better.',
  'The best time to plant a tree was twenty years ago. The second-best time was July 3.',
  'Streetlights do not compete with the dawn. They hand it the city and go dark.',
  'You do not need a bigger engine. You need fewer anchors.',
  'The month owes you nothing. It gave you all of its mornings.',
  'Endings that arrive on schedule are not tragedies. August is allowed in.',

  /* — August : heat and craft — */
  'Heat teaches patience the way winter never could: by making hurry ridiculous.',
  'Do less today, entirely.',
  'The cicada waits seventeen years, sings for six weeks, and regrets nothing.',
  'Slow is smooth, smooth is fast. The harbor knew it first.',
  'Genius is mostly the refusal to be bored by the fundamentals.',
  'A sailboat cannot sail straight into the wind, and yet it gets there. Tack.',
  'The lawn you envy is watered by someone at five in the morning. Envy the waking, not the lawn.',
  'Craft is love with the deadline removed.',
  'Even the sun spends half its time below your horizon. Output is not identity.',
  'August light is honest light. Look at your work in it.',
  'You cannot skim a summer.',
  'The ivy took the wall one brick at a time, and now it owns the college.',
  'Perfection is a direction, not an address.',
  'Somewhere in the city a beginner just started. Protect them; you were them.',
  'The dog days ask one question: can you be kind while uncomfortable?',
  'Attention is the only currency that spends itself.',
  'A pier stands because most of it is invisible and wet. Respect your foundations.',
  'Say no like the drawbridge: politely, on schedule, without apology.',
  'What if the goal were to be trustworthy, and everything else were weather?',
  'The meteor shower peaks whether or not the sky is clear. Work like that.',
  'Every master was once a disaster with a library card.',
  'Cool nights are coming. Nothing gold has to stay for it to have been gold.',
  'A thing almost finished is a different species from a thing finished.',
  'The lighthouse never chases ships.',
  'Fall asleep earlier tonight. That is the whole strategy.',
  'The city cooled ten degrees at sunset and no one thanked the ocean.',
  'You were not behind. You were early to a different schedule.',
  'Wisdom is knowing which fires are just weather.',
  'The last week of summer is still summer. Do not grieve what you are holding.',
  'August leaves like a guest who knows when to go: warmly, without a scene.',
  'September will ask what you practiced all summer. Answer honestly.',

  /* — September : begin again — */
  'The whole city smells like sharpened pencils. Begin again.',
  'Every September, Boston doubles in students and hope. Both are renewable.',
  'Learning looks like losing for the first while. Stay past the first while.',
  'The light is leaving three minutes a day now. Spend them on purpose.',
  'You do not find time. You defend it.',
  'A syllabus is a promise to your future self, written in public.',
  'The maples turn first at the edges. Big changes start as edges.',
  'Write it down. The faintest ink outlives the sharpest memory.',
  'Being teachable at forty is worth more than being brilliant at twenty.',
  'The equinox splits the day evenly and asks you to do the same with your worry.',
  'Cold mornings, warm afternoons: the year practicing its goodbye.',
  'Read one page. The book has no other plan for you.',
  'The geese do not hold meetings about leaving. They feel it and go.',
  'A question held open is worth ten answers rushed.',
  'Sweater weather is the year forgiving you.',
  'The tide chart does not argue. It just tells you when.',
  'What you did today is what you are becoming. Small print, binding contract.',
  'October is loading. Nothing to do but be worth falling on.',
  'The harbor seals come back without being asked. So can your discipline.',
  'Do not confuse the buzz of noise with the hum of work.',
  'The first cold rain rinses the summer off the streets. Let it.',
  'Curiosity is the only engine that runs better with age.',
  'A single lit window at six in the morning is the most hopeful thing in any city.',
  'You cannot edit a blank page, but you can absolutely edit a bad one.',
  'The last warm day will not announce itself. Treat every candidate accordingly.',
  'Apples do not apologize for taking all year.',
  'The river routes around the rock. The rock thinks it won. The river is gone.',
  'Your future self is eavesdropping on today. Say something useful.',
  'The dark is not coming for you. It is coming for the light\u2019s shift change.',
  'September ends mid-sentence, the way all good chapters do.',

  /* — October : letting go, gorgeously — */
  'The trees spend October proving that letting go can be done gorgeously.',
  'Every leaf falls exactly once, and makes it count.',
  'Peak color lasts a week. Attend.',
  'A pumpkin is ninety percent water and one hundred percent committed.',
  'The frost tonight is the first draft of winter. Read it closely.',
  'You rake knowing more leaves will fall. That is not futility. That is tending.',
  'The dark at six is not a loss. It is a room you forgot you owned.',
  'Some things must be released at the exact moment they are most beautiful.',
  'Fog on the harbor all morning: even the city gets to think.',
  'Nothing in the woods is trying to be seen, and all of it is worth seeing.',
  'The wind did the raking overnight, badly. Nature ships fast and iterates.',
  'Old sweaters and old friends: both warmer for the wear.',
  'Spring marathons are made of October mornings.',
  'A candle loses nothing by lighting another candle. Still, mind your wick.',
  'The last tomato ripens on the windowsill: out of season, exactly on time.',
  'What the tree drops feeds the tree. Waste is a failure of imagination.',
  'The streetlights come on at 5:40 now, softly, like the city clearing its throat.',
  'Being cold for one minute is the fastest honest thing you will do all day.',
  'The squirrels are not anxious. They are prepared. There is a difference.',
  'Half the year is behind this line. Turn around slowly and admire it.',
  'A bare branch is not dead. It is fluent in a language with a long winter in it.',
  'Rain on the window at night: the oldest subscription, still worth it.',
  'The corn maze only works because you cannot see over it. So does life.',
  'Hot cider exists. Some problems have solutions.',
  'The clocks fall back soon. One free hour: spend it asleep.',
  'A jack-o\u2019-lantern is a vegetable doing its best. Same.',
  'Courage in October looks like starting something that finishes in spring.',
  'The last leaves hold on, not from fear but from stubborn joy. Pick your reason.',
  'Even the ivy turns scarlet. Even the steady ones get to change.',
  'Dusk at 5:30, and the windows of the city come on like slow applause.',
  'October leaves the way it came: on fire, unbothered.',

  /* — November : the coat comes off — */
  'November is the month with its coat off, telling you the truth.',
  'Bare trees show you the birds\u2019 nests. Loss is also disclosure.',
  'The first flurries do not accumulate. Neither do the first tries. Keep snowing.',
  'Gratitude is attention with the volume up.',
  'Dark at 4:30 is the sky handing you the evening back. Take it.',
  'Soup season: long problems, low heat.',
  'The harbor is slate gray and completely unbothered. Aspire.',
  'What you are grateful for grows a handle you can hold in the dark.',
  'Frost writes on every windshield and never signs its work.',
  'The wind off the water has an editor now. Every walk is shorter and truer.',
  'Rest more. The trees do it in public and no one calls them lazy.',
  'A candle in a dark room does arithmetic no spreadsheet can follow.',
  'The last leaf on the block fell today. Somebody had to be last. It still counted.',
  'Wool socks are a technology. Gratitude is a technology. Use your tools.',
  'Thank one person who has no idea they helped you.',
  'The table matters more than the menu.',
  'Early dark, late dawn: the year narrows to a hallway. Walk it.',
  'What survived the frost was always the point of the garden.',
  'The squirrel forgets most of the acorns it buries. Forests forgive imperfect memory.',
  'Cold hands, warm pockets: half of comfort is knowing where things go.',
  'The city lights come on at 4:15 now and hold the sky up all evening.',
  'Write the letter you keep composing in the shower.',
  'Silence in November is not empty. It is the sound of everything conserving.',
  'A month of gray teaches your eye to find twelve kinds of gray.',
  'The ferry runs in cold rain, on schedule, hot coffee below deck. Be the ferry.',
  'You have survived one hundred percent of your Novembers.',
  'The first real snow forgives every ugly corner of the city at once.',
  'Short days concentrate. So can you.',
  'The dark this month is a hallway, and December is carrying the lights.',
  'November ends like a held breath. Let it go.',

  /* — December : the light turns — */
  'December begins: the year\u2019s last chapter, and the one with all the lamps in it.',
  'Cold air is candid air. Big questions travel better in it.',
  'String lights exist because someone refused to concede the dark. Refuse it too.',
  'The tree on the Common gets lit this week. The city insists on joy, annually.',
  'Wrap something badly with your whole heart. It will be the favorite.',
  'The sun sets at 4:12 and the sky apologizes in rose and gold.',
  'What you finish this month counts double. What you forgive counts triple.',
  'Snow is weather that asks you to look up with your mouth open. Comply.',
  'The year is not grading you. It is just ending, the way rivers reach the sea.',
  'Buy the good coffee. It is December.',
  'The solstice is close. The dark has nearly finished its argument.',
  'A finished small thing beats a grand plan wintering in your head.',
  'Boston at dusk in December is a painting no museum can hold. Free, daily.',
  'Somebody\u2019s whole December is one kind message away. Send it.',
  'The harbor does not freeze easily. Salt and motion. Remember both.',
  'Ten days left in the dark\u2019s advance. Then the light turns and comes back.',
  'Every window with a candle in it is someone keeping a small promise.',
  'The longest night is also the turning night. Hold on and watch.',
  'Solstice week: for a few days the sun stands still, and so may you.',
  'Today the light starts coming back. Seconds only — but the direction changed.',
  'The days lengthen from here. Every spring you ever loved began this week.',
  'The old year is folding its ledger. December keeps stories, not balances.',
  'Snow at night under streetlights: the ordinary, interrupted by grace.',
  'Give something away quietly, and keep the receipt in your chest.',
  'It is Christmas in the city. Even the traffic sounds a little like bells.',
  'Leftovers, long walks, low light: the week the year exhales.',
  'Look back only to count what grew. The tree did. So did you.',
  'Write down one thing 2026 taught you, before 2027 starts talking.',
  'The last days of a year are a harbor. Everything slows to come home.',
  'Tomorrow night the year ends. Tonight, just notice everything.',
  'Day 182. The tree is grown. The letter is open. Welcome back.',
];

/** The line and caption for a given moment. */
export function lineFor(now) {
  const day = Math.floor(daysBetween(PLANTED, now)); // 0 on July 3, 2026
  if (day < 0) {
    return { text: LINES[0], caption: 'Line 1 of 182 · set down July 3, 2026' };
  }
  if (day < LINES.length) {
    return {
      text: LINES[day],
      caption: `Line ${day + 1} of 182 · set down July 3, 2026`,
    };
  }
  const idx = day % LINES.length;
  return {
    text: LINES[idx],
    caption: `Line ${idx + 1} of 182 · from the 2026 almanac, returning like a tide`,
  };
}
